# This is a basic workflow to help you get started with Actions

name: Build and Push Documentation to Github Pages

on:
  release:
    types: 
      - published

  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Build and Push
      uses: TypeStrong/typedoc-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
